export {
    headerText,
    tooltipText,
    dropdownValue,
    departments,
    contentText,
    tableEmployeeCollumn,
    tableMissionAllownEmployee,
    statusDropdown,
    ErrorMessage,
    tableMissionDetail,
    popupMessage,
    filter,
    setting,
    feature,
    statusText,
    placeholder,
    title,
    misionListText,
    missionDetailText,
    toastMessage,
};

var headerText = {
    webTitle: "Timekeeping",
    headerOverview: "Overview",
    headerEstablish: "Establish",
    webVersion: "RC23.",
    notification: "Notify",
    all: "All",
    userName: "QM",
    userFullName: "Quang Minh",
    email: "nguyenqm2001@gmail.com",
    companyName: "CTY TNHH NGỌC THANH TÂM",
    changePass: "Change Password",
    accountSetting: "Account settings",
    securitySetting: "Security settings",
    introducingPoints: "Introducing points",
    languageVie: "Language: Viet Nam",
    languageEng: "Language: English",
    vie: "Viet Nam",
    eng: "English",
    logOut: "Log out",
};
var tooltipText = {
    bell: "Notification",
    help: "Help",
    feature: "Other features",
    refresh: "Reload",
    filter: "Filter",
    export: "Export",
    setting: "Customize columns",
};
const dropdownValue = {
    timeKeepingText: "Timekeeping",
    shiftText: "Shift",
    orderManagementText: "Order Management",
    reportText: "Report",
    timeKeeping: ["Detailed timesheet", "Summary timesheet", "Attendance data"],
    shift: ["General shift table", "Detailed shift", "Shifts"],
    orderManagement: [
        "Application for leave",
        "Register late, leave early",
        "Sign up to do more",
        "Recommend to update",
        "Recommend to go to work",
        "Recommend changing shifts",
        "Approval of attendance",
        "Leave summary table",
        "Summary table of compensatory leave",
        "Leave plan",
    ],
    report: [
        "Report going early and coming back late",
        "Summary report on the situation of being late",
        "Planned leave status",
        "List of parks for business trips",
        "Report the list of overtime employees",
        "Analysis of overtime situation",
        "Summary report on employee's overtime",
        "Report on the situation of employees going on business trips",
    ],
    pageSize: [15, 25, 50, 100],
    status: ["All", "Pending", "Approved", "Refuse"],
};

const departments = [
    {
        expanded: true,
        departmentID: "1",
        departmentName: "CTY TNHH NGỌC THANH TÂM",
        items: [
            {
                departmentID: "1_1",
                departmentName: "Hồ Hàng Hải - 56",
                items: [
                    {
                        departmentID: "1_1_1",
                        departmentName: "Đỗ Đức Dục",
                    },
                    {
                        departmentID: "1_1_2",
                        departmentName: "Cầu Giấy",
                    },
                ],
            },
            {
                departmentID: "1_2",
                departmentName: "Bánh Kẹo - cana",
                items: [
                    {
                        departmentID: "1_2_1",
                        departmentName: "Hà Đông",
                    },
                    {
                        departmentID: "1_2_2",
                        departmentName: "Trần Nhật Quyết",
                    },
                ],
            },
            {
                departmentID: "1_3",
                departmentName: "Cơ sở Phố hàng Bài",
            },
            {
                departmentID: "1_4",
                departmentName: "Hoàng Minh Giám",
            },
            {
                departmentID: "1_5",
                departmentName: "Lê Đức Thọ",
            },
        ],
    },
];
const contentText = {
    webTitle: "Recommend to go to work",
    export: "Import",
    statusText: "Status",
    totalRecords: "Total records:",
    recordText: "records",
};

const tableEmployeeCollumn = [
    {
        fixed: false,
        fixedPosition: "left",
        visible: false,
        caption: "Employee ID",
        dataField: "employeeID",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: true,
        fixedPosition: "left",
        visible: true,
        caption: "Employee code",
        dataField: "employeeCode",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: true,
        fixedPosition: "left",

        visible: true,
        caption: "Requester",
        dataField: "employeeName",
        alignment: "left",
        dataType: "text",
        minWidth: "250",
        cellTemplate: "name-cell",
    },
    {
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "Job position",
        dataField: "jobPositionName",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "Working department",
        dataField: "organizationUnitName",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        alignment: "center",
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "Request date",
        dataField: "requestDate",
        alignment: "center",
        dataType: "datetime",
        minWidth: "150",
        cellTemplate: "requestDate",
    },
    {
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "Start date",
        dataField: "fromDate",
        alignment: "center",
        dataType: "datetime",
        minWidth: "150",
        cellTemplate: "fromDate",
    },
    {
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "End date",
        dataField: "toDate",
        alignment: "center",
        dataType: "datetime",
        minWidth: "150",
        cellTemplate: "toDate",
    },
    {
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "Leave day",
        dataField: "leaveDay",
        alignment: "right",
        dataType: "float",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",

        visible: true,
        caption: "Place of bussiness trip",
        dataField: "location",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "Reason for bussiness trip",
        dataField: "purpose",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "Request",
        dataField: "request",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",

        visible: true,
        caption: "Support name",
        dataField: "supportNames",
        alignment: "left",
        dataType: "text",
        minWidth: "200",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",

        visible: true,
        caption: "Approver",
        dataField: "approvalName",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",

        visible: true,
        caption: "Relationship name",
        dataField: "relationShipNames",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",

        visible: true,
        caption: "Description",
        dataField: "description",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "",
    },
    {
        fixed: false,
        fixedPosition: "left",
        visible: true,
        caption: "Status",
        dataField: "status",
        alignment: "left",
        dataType: "text",
        minWidth: "150",
        cellTemplate: "grid-cell",
    },
    {
        fixed: true,
        fixedPosition: "right",
        visible: true,
        caption: "",
        dataField: "",
        alignment: "center",
        dataType: "text",
        minWidth: "100",
        cellTemplate: "feature-cell",
    },
];

const tableMissionAllownEmployee = [
    {
        fixed: true,
        visible: true,
        caption: "Employee code",
        dataField: "employeeCode",
        alignment: "left",
        dataType: "text",
    },
    {
        fixed: true,
        visible: true,
        caption: "Employee name",
        dataField: "employeeName",
        alignment: "left",
        dataType: "text",
        cellTemplate: "name-cell",
    },
    {
        fixed: true,
        visible: true,
        caption: "Working department",
        dataField: "organizationUnitName",
        alignment: "left",
        dataType: "text",
    },
    {
        fixed: true,
        visible: true,
        caption: "Job position",
        dataField: "jobPositionName",
        alignment: "left",
        dataType: "text",
    },
    {
        fixed: true,
        visible: true,
        caption: "Mobile phone",
        dataField: "mobilePhone",
        alignment: "left",
        dataType: "text",
    },
];

const tableMissionDetail = [
    {
        fixed: false,
        caption: "Employee code",
        dataField: "employeeCode",
        minWidth: 150,
        cellTemplate: "",
    },
    {
        fixed: false,
        caption: "Employee name",
        dataField: "employeeName",
        minWidth: 150,
        cellTemplate: "name-cell",
    },
    {
        fixed: false,
        caption: "Job position",
        dataField: "jobPositionName",
        minWidth: 150,
        cellTemplate: "",
    },
    {
        fixed: false,
        caption: "Working department",
        dataField: "organizationUnitName",
        minWidth: 150,
        cellTemplate: "",
    },
    {
        fixed: false,
        caption: "Mobile phone",
        dataField: "mobilePhone",
        minWidth: 150,
        cellTemplate: "",
    },
    {
        fixed: true,
        fixedPosition: "right",
        caption: "",
        minWidth: 100,
        cellTemplate: "delete-cell",
    },
];

const statusDropdown = [
    {
        statusName: "Pending",
        id: 0,
    },
    {
        statusName: "Approved",
        id: 1,
    },
    {
        statusName: "Refuse",
        id: 2,
    },
];
const popupMessage = {
    deleteEmployeeMsg1: "Are you sure you want to delete",
    deleteEmployeeMsg2: "from employees going to work?",
};

const filter = [
    "Employee code",
    "Proposer",
    "Job position",
    "Request date",
    "From date",
    "To date",
    "Leave days",
    "Location",
    "Purpose",
    "Request",
    "Support name",
    "Approval name",
    "Relationship name",
    "Note",
];
const setting = [
    "Employee code",
    "Proposer",
    "Job position",
    "Request date",
    "From date",
    "To date",
    "Leave days",
    "Location",
    "Purpose",
    "Request",
    "Support name",
    "Approval name",
    "Relationship name",
    "Note",
    "Status",
];
const feature = [
    {
        class: "icon-infor-servise",
        text: "Information Services",
    },
    {
        class: "icon-start-using",
        text: "Start using",
    },
    {
        class: "icon-new",
        text: "New feature",
    },
    {
        class: "icon-support-major",
        text: "Career guildline",
    },
    {
        class: "icon-useful-knowledge",
        text: "Useful knowledge",
    },
    {
        class: "icon-online-course",
        text: "Online Courses",
    },
];
const statusText = {
    NotApproved: "Pending",
    Approved: "Approved",
    Refuse: "Refuse",
};
const placeholder = {
    seacrh: "Search",
    allOganization: "All organization units",
};
const title = {
    add: "Add",
    filter: "Filter",
    apply: "Apply",
    refuse: "Refuse",
    accept: "Accept",
    export: "Export",
    delete: "Delete",
    back: "Return",
    nextPage: "Next page",
    warning: "Warning",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    addEmployee: "Add employee",
    notification: "notification",
    choose: "Choose",
    dontSave: "Don't save",
    default: "Default",
    noFilter: "Remove filter",
};
const misionListText = {
    selected: "Selected",
    deSelected: "Deselect",
    from: "From",
    to: "to",
    custonCollumn: "Customize columns",
    filter: "Filter",
    deleteMsg: "Are you sure you want to delete this form?",
    multiDeleteMsg:
        "Are you sure you want to delete these selected applications?",
    sure: "Are you sure",
    selectedApplication: "selected application?",
};
const missionDetailText = {
    titleEdit: "Edit proposal for business trip",
    titleAdd: "Add a new proposal for a business trip",
    title: "Details of the proposal for a business trip",
    employeeName: "Requester",
    oganizationName: "Working department",
    requestDate: "Request date",
    fromDate: "Start date",
    toDate: "End date",
    leaveDay: "Leave day",
    Location: "Place of bussines trip",
    purpose: "Reason for bussines trip",
    request: "Request",
    support: "Support name",
    approvedName: "Approver",
    relationship: "Relationship name",
    status: "Status",
    tableTitle: "List of employees on business trips",
    selected: "Selected",
    deSelected: "Deselected",
    remove: "Remove",
    noData: "No data found",
    add: "Add",
    totalRecord: "Total records:",
    note: "Note",
    name: "QM",
    ESC: "Press ESC to ",
    all: "All",
    activityDiary: "Activity Log",
    inforChange: "The information has been changed do you want to save it?",
};

const ErrorMessage = {
    requiredToDate: "The return date cannot be empty",
    invalidDate:
        "The return date must be greater than or equal to the departure date",
    requiredFromDate: "Departure date cannot be empty",
    invalidFromDate:
        "Departure date must be less than or equal to departure date",
    employeeMessage: "Proposer cannot be empty",
    requestDateMessage: "Request date cannot be empty",
    locaionMessage: "Location cannot be empty",
    purposeMessage: "Purpose cannot be empty",
    approvedMessage: "Aprroval cannot be empty",
    statusMessage: "Status cannot be empty",
};

const toastMessage = {
    addSuccess: "Successfully added new",
    editSuccess: "Successfully edited",
    deleteSuccess: "Delete successfully",
    refuseSuccess: "Successfully refused",
    approvedSuccess: "Successfully approved",
    addFail: "Add new failure",
    editFail: "Edited failure",
    deleteFail: "Delete failure",
    refuseFail: "Failure refused",
    approvedFail: "Failure approved",
    messageFail: "Please contact Misa",
};
